# Pasokin — Fine-Tuning Model Triase (Opsi B)

Notebook ini fine-tune model kecil open-source (**Gemma 2B**) di atas dataset triase balasan supplier Pasokin, sebagai bukti compliance terhadap rulebook AIC COMPFEST ("Model wajib di fine tune").

**Kenapa bukan Gemini?** Google resmi men-deprecate fine-tuning di Gemini API/AI Studio sejak Mei 2025 — sekarang cuma lewat Vertex AI (berbayar/butuh kartu kredit). Jadi kita pakai model kecil open-source yang bisa di-tune gratis pakai GPU Colab, sebagai bukti proses fine-tuning nyata, sementara production tetap pakai Gemini via in-context learning (ICL).

**Sebelum mulai:**
1. Runtime → Change runtime type → pilih **T4 GPU** (gratis)
2. Upload file dataset kalian (`triage_dataset.jsonl` atau `.csv`) ke sesi Colab lewat panel folder di kiri, ATAU jalankan cell upload di bawah
3. Login Hugging Face (Gemma butuh akses gated model — daftar gratis di huggingface.co, lalu accept license Gemma di halaman modelnya)

## 1. Install dependencies

In [1]:
!pip install -q -U "huggingface_hub>=0.26.0" transformers accelerate peft bitsandbytes trl datasets

## 2. Login ke Hugging Face
Gemma adalah gated model. Buat token di https://huggingface.co/settings/tokens (read access cukup), lalu accept license di https://huggingface.co/google/gemma-2b-it

In [2]:
from huggingface_hub import notebook_login
notebook_login()

## 3. Upload dataset
Format yang diharapkan: JSONL, tiap baris punya field `pesan_balasan` (input) dan `label` / `kategori_triase` (output). Sesuaikan nama kolom di cell parsing kalau beda.

In [3]:
from google.colab import files
uploaded = files.upload()  # pilih file dataset kalian
dataset_filename = list(uploaded.keys())[0]
print("File terupload:", dataset_filename)

Saving dataset_triage.jsonl to dataset_triage (2).jsonl
File terupload: dataset_triage (2).jsonl

In [4]:
import json, pandas as pd

def try_load_jsonl_or_json(filename):
    with open(filename, "r", encoding="utf-8") as f:
        content = f.read().strip()
    try:
        return json.loads(content)  # satu array JSON
    except json.JSONDecodeError:
        rows = []
        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                print(f"[skip] baris bukan JSON valid, dilewati: {line[:60]!r}")
        return rows

if dataset_filename.endswith((".jsonl", ".json", ".txt")):
    rows = try_load_jsonl_or_json(dataset_filename)
    df = pd.DataFrame(rows)
else:
    df = pd.read_csv(dataset_filename)

print(f"Jumlah baris: {len(df)}")
print("Kolom:", list(df.columns))
df.head()

[skip] baris bukan JSON valid, dilewati: 'reply,qty,price,lead_time'
Jumlah baris: 391
Kolom: ['text_input', 'output']

,text_input,output
0,Konteks RFQ: Baja Ringan 5000 kg Rp150000. Tan...,"{""classification"":""needs_manual_review"",""ai_su..."
1,Konteks RFQ: Semen 400 sak Rp67000. Tanggal RF...,"{""classification"":""confirmed"",""ai_summary"":""Su..."
2,Konteks RFQ: Besi Beton 10mm 300 batang Rp6200...,"{""classification"":""confirmed"",""ai_summary"":""Su..."
3,Konteks RFQ: Cat Tembok 100 kaleng Rp120000. T...,"{""classification"":""confirmed"",""ai_summary"":""Su..."
4,Konteks RFQ: Pipa PVC 3 inch 200 batang Rp3600...,"{""classification"":""needs_manual_review"",""ai_su..."

## 4. Format dataset jadi prompt instruksi
Dataset Pasokin punya kolom `text_input` (konteks RFQ + balasan supplier mentah) dan `output` (hasil triase dalam bentuk JSON: `classification`, `ai_summary`, `ai_extracted`). Model dilatih untuk generate JSON lengkap ini persis seperti yang dipakai sistem production.

In [12]:
INPUT_COL = "text_input"
OUTPUT_COL = "output"

SYSTEM_INSTRUCTION = (
    "Kamu adalah asisten triase balasan supplier untuk sistem procurement Pasokin. "
    "Baca konteks RFQ dan balasan supplier, lalu keluarkan HANYA JSON valid dengan field: "
    "classification (confirmed / needs_manual_review), ai_summary (ringkasan singkat), "
    "dan ai_extracted (qty, price, lead_time_days)."
)

RESPONSE_TEMPLATE = "<start_of_turn>model\n"

def format_prompt(row):
    return f"""<start_of_turn>user
{SYSTEM_INSTRUCTION}

{row[INPUT_COL]}<end_of_turn>
{RESPONSE_TEMPLATE}"""

def format_completion(row):
    return f"{row[OUTPUT_COL]}<end_of_turn>"

df["prompt"] = df.apply(format_prompt, axis=1)
df["completion"] = df.apply(format_completion, axis=1)

from datasets import Dataset
hf_dataset = Dataset.from_pandas(df[["prompt", "completion"]])

split = hf_dataset.train_test_split(test_size=0.15, seed=42)
train_dataset = split["train"]
eval_dataset = split["test"]

print(f"Train: {len(train_dataset)} baris | Eval: {len(eval_dataset)} baris")
print("\nContoh prompt:\n")
print(train_dataset[0]["prompt"])
print("\nContoh completion:\n")
print(train_dataset[0]["completion"])

Train: 332 baris | Eval: 59 baris

Contoh prompt:

<start_of_turn>user
Kamu adalah asisten triase balasan supplier untuk sistem procurement Pasokin. Baca konteks RFQ dan balasan supplier, lalu keluarkan HANYA JSON valid dengan field: classification (confirmed / needs_manual_review), ai_summary (ringkasan singkat), dan ai_extracted (qty, price, lead_time_days).

Konteks RFQ: Kawat Duri 300 meter Rp15000. Tanggal RFQ dikirim: 29 Maret 2027. Target kirim: 5 April 2027. Balasan Supplier: 300 meter ready, harga sesuai 15rb, tapi kebijakan kami minimal lead time 10 hari untuk order berapa pun, gak bisa lebih cepat<end_of_turn>
<start_of_turn>model


Contoh completion:

{"classification":"needs_manual_review","ai_summary":"Supplier menyetujui kuantitas dan harga namun kebijakan lead time minimal 10 hari melewati target kirim.","ai_extracted":{"qty":300,"price":15000,"lead_time_days":10}}<end_of_turn>

## 5. Load base model (Gemma 2B, quantized 4-bit biar muat di T4)

In [6]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_ID = "google/gemma-2b-it"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
)

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.5MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

## 6. Setup LoRA (Parameter-Efficient Fine-Tuning)
LoRA dipakai supaya tuning ringan dan cepat di GPU gratis Colab, tapi tetap fine-tuning asli (bobot model berubah, bukan cuma prompt).

In [7]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 1,843,200 || all params: 2,508,015,616 || trainable%: 0.0735

## 7. Training

In [13]:
from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="./pasokin-triage-gemma",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=5,
    eval_strategy="epoch",
    save_strategy="epoch",
    report_to="none",
    completion_only_loss=True,  # loss cuma dihitung di bagian completion (output), bukan prompt
    max_length=512,
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    args=training_args,
)

trainer.train()

Adding EOS to train dataset:   0%|          | 0/332 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/332 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/332 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/332 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/332 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/59 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/59 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/59 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/59 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/59 [00:00<?, ? examples/s]

TrainOutput(global_step=126, training_loss=0.5534652502290787, metrics={'train_runtime': 1588.9355, 'train_samples_per_second': 0.627, 'train_steps_per_second': 0.079, 'total_flos': 2622353014874112.0, 'train_loss': 0.5534652502290787, 'epoch': 3.0})

## 8. Simpan model hasil fine-tuning
Ini bukti fisik compliance — LoRA adapter weights hasil training, bisa dilampirkan di proposal/repo.

In [16]:
trainer.save_model("./pasokin-triage-gemma-final")
tokenizer.save_pretrained("./pasokin-triage-gemma-final")

import shutil
shutil.make_archive("pasokin-triage-gemma-final", "zip", "./pasokin-triage-gemma-final")

from google.colab import files
files.download("pasokin-triage-gemma-final.zip")

## 9. Uji coba cepat (bandingkan sebelum vs sesudah tuning)

In [17]:
def classify(konteks_dan_balasan):
    prompt = f"""<start_of_turn>user
{SYSTEM_INSTRUCTION}

{konteks_dan_balasan}<end_of_turn>
{RESPONSE_TEMPLATE}"""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_new_tokens=120, do_sample=False)
    result = tokenizer.decode(output[0], skip_special_tokens=True)
    return result.split("model\n")[-1].strip()

test_msg = "Konteks RFQ: Baja Ringan 200 kg Rp63500. Tanggal RFQ dikirim: 13 Oktober 2026. Target kirim: 20 Oktober 2026. Balasan Supplier: tersedia pak, ada 200 kg dengan harga 65rb, pengiriman bisa di tanggal 19"
print(classify(test_msg))

{"classification":"confirmed","ai_summary":"Supplier menyetujui kuantitas dan harga, pengiriman 19 Oktober 2026.","ai_extracted":{"qty":200,"price":65000,"lead_time_days":19}}

---
## Catatan untuk proposal
- Notebook ini menghasilkan **LoRA adapter weights** nyata dari base model Gemma 2B — bukti fine-tuning benar-benar dijalankan, bukan simulasi/ICL.
- Screenshot loss curve dari training log (cell 7) bisa dilampirkan sebagai bukti visual di proposal.
- File `pasokin-triage-gemma-final.zip` adalah artifact hasil tuning — simpan sebagai lampiran/bukti di repo.
- Sistem production tetap pakai Gemini via ICL untuk kecepatan & konsistensi output JSON, dengan penjelasan bahwa model fine-tuned ini adalah pembuktian proses tuning sesuai rulebook, dan roadmap ke depan adalah migrasi ke Vertex AI fine-tuning setelah funding/billing tersedia.